//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_FINAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("domicilio")]
    public partial class domicilio
    {
        [Key]
        public int id { get; set; }
        public int idventa { get; set; }
        public int idcliente { get; set; }
        public string direccion { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual venta venta { get; set; }
    }
}
